fixed broken code blocks and fixed indentation (made it consistent)
CarmenPopoviciu/protractor-testing-guidelines pull request #39
Opened 2017-03-22 18:22 UTC by basdp

2017-03-29 10:46 UTC, basdp commented
@CarmenPopoviciu bump :-)

2017-05-16 19:47 UTC, basdp commented
@CarmenPopoviciu Are you still alive? :-( I'm worried!

2017-05-17 06:29 UTC, robinj commented
Is this commit just a reformat of the code or are there changes? I am trying to understand what exactly has changed, since mass reformatting of files tends to cause the diff tool to be less helpful.

2017-05-17 06:31 UTC, basdp commented
No, this is just formatting and styling. No changes to the code or text at all.

2017-08-09 20:52 UTC, LeviSchuck commented
Why isn't this accepted and merged yet?

2017-08-17 09:31 UTC, robinj requested changes
Please split the reformatting and actual changes into two commits/PRs to make the history clearer

2017-08-17 09:36 UTC, basdp commented
@robinj there are no actual changes.

2017-08-17 09:42 UTC, robinj commented on README.md
> +           seleniumAddress: dev_Se,
Please separate this change into a separate commit

2017-08-17 09:42 UTC, robinj commented
@basdp I have commented where the change is

2017-10-16 11:31 UTC, LayZeeDK commented
#40 fixed the rendering of the code blocks.

2017-10-16 16:28 UTC, robinj commented
@layzeedk agreed

2017-10-16 16:28 UTC, closed without merging