Reviewed the intro and altered some stuff for clearification
CarmenPopoviciu/protractor-testing-guidelines pull request #8
Opened 2015-01-15 17:27 UTC by zwanz0r

Explanation of the changes I made:

*Again, it is very important to keep in mind, that just like with unit tests, e2e tests are black-box* 
Is that true? I've seen many unittests which are white box. For example if you have a controller which uses a $resource service to do an API call. Then there are teams that whould inject a mock for that service and verify that the service is called correctly (whitebox). I allways like to use the $httpBackend to verify the actual HTTP communication is correct (blackbox)

*you'll probably remember about the Angular Scenario Runner*
Mentioning the term "karmaE2E" here. This is the biggest advantage I think. It will act as a user, instead it manipulated the DOM using javascript. This is why you should migrate to protractor ASAP.

*Protractor is an e2e test framework build on top of WebDriverJS*
Mention that WebDriverJS is the selenium API for javascript. More people will know Selenium.

* }:) output :o all sort o/ of funny :P smileys everywhere ;).*
Did ;) you ;0 want :P to (: leave :> them >:x in?

2016-02-20 17:54 UTC, brutalcrozt commented
:+1:

2017-10-16 10:35 UTC, robinj requested changes

2017-10-16 10:35 UTC, robinj commented on README.md
> +It is very important to keep in mind that, maybe contrary to unit tests, e2e tests are black-box tests and only
Remove "maybe". Be more sure of your assertion 🙂

2017-10-16 10:35 UTC, robinj commented on README.md
> +reconsider migrating to protractor.
Change "reconsider" to "consider"

2017-10-16 10:41 UTC, robinj approved these changes

2017-10-16 10:41 UTC, merged